#!/usr/bin/env python3
import sys

from rqt_gui.main import Main

from mp_test_ui.mp_test import MpTest

plugin = 'mp_test_ui.mp_test.MpTest'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))